{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
    component: mongodb
spec:
  clusterIP: None
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongo
{{- end }}
