{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: be-redis-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
    component: redis
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: be-redis
{{- end }}
