{{- if and .Values.mongodb.enabled (not .Values.mongodb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
    component: mongodb
type: Opaque
data:
  username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  password: {{ .Values.mongodb.auth.password | b64enc | quote }}
{{- end }}
