{{- if .Values.worker.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-analyzer-shared-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.worker.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.worker.pvcStorage | quote }}
{{- end }}
---
{{- if .Values.dindCache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-cache-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.dindCache.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.dindCache.storage | quote }}
{{- end }}